version: "3.8"

services:

  soc-db:
    container_name: soc-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - psqlvolume:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  soc-pgadmin:
    container_name: soc-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: soc-user@soc.com
      PGADMIN_DEFAULT_PASSWORD: soc-user
    volumes:
      - pgadminvolume:/root/.pgadmin
    ports:
      - "8085:80"
    restart: unless-stopped

volumes:
  psqlvolume: null
  pgadminvolume: null 